openapi: 3.1.0 #versionen av OpenAPI-specifikationen.
info:
  title: Bekräfta beslut API
  version: 1.0.0
  description: API för att registrera avslag eller bekräfta beslut på ersättningar.

paths:
  /regel/bekraftabeslut/{handlaggningId}:
    get:
      summary: Hämta information som behövs för att utföra kontrollen
      description: Hämta information som behövs för att utföra kontrollen
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: ID för handläggningsärendet
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Information hämtad OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDataResponse"
        "404":
          description: Informationen hittades inte
    patch:
      summary: Uppdatera om kunden har rätt till premie
      description: Uppdatera om kunden har rätt till premie
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: ID för handläggningsärendet
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchDataRequest"
      responses:
        "200":
          description: Uppdatering genomförd OK
        "404":
          description: Informationen hittades inte

  /regel/bekraftabeslut/yrkandestatus:
    get:
      tags: [BekraftaBeslutController]
      operationId: getYrkandestatus
      summary: Hämta möjliga alternativ för yrkandestatus
      description:  Hämta möjliga alternativ för yrkandestatus
      responses:
        "200":
          description: Information hämtad OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Referensdata"

  /regel/bekraftabeslut/avslutstyp:
    get:
      tags: [BekraftaBeslutController]
      operationId: getAvslutstyp
      summary: Hämta möjliga alternativ för avslutstyp
      description:  Hämta möjliga alternativ för avslutstyp
      responses:
        "200":
          description: Information hämtad OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Referensdata"

  /regel/bekraftabeslut/beslutstyp:
    get:
      tags: [BekraftaBeslutController]
      operationId: getBeslutstyp
      summary: Hämta möjliga alternativ för beslutstyp
      description:  Hämta möjliga alternativ för beslutstyp
      responses:
        "200":
          description: Information hämtad OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Referensdata"

  /regel/bekraftabeslut/beslutsutfallstyp:
    get:
      tags: [BekraftaBeslutController]
      operationId: getBeslutsutfallstyp
      summary: Hämta möjliga alternativ för beslutsutfallstyp
      description:  Hämta möjliga alternativ för beslutsutfallstyp
      responses:
        "200":
          description: Information hämtad OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Referensdata"


components:
  schemas:
    GetDataResponse:
      type: object
      properties:
        handlaggning_id:
          type: string
          format: uuid
        kund:
          $ref: "#/components/schemas/Kund"
        ersattning:
          type: array
          items:
            $ref: "#/components/schemas/Ersattning"

    PatchDataRequest:
      type: object
      properties:
        ersattningar:
          type: array
          items:
            $ref: '#/components/schemas/UpdateErsattning'
        beslut:
          $ref: '#/components/schemas/Beslut'
          description: Övergripande beslut för specificerade ersättningar
      required:
        - ersattningar
        - beslut

    Beslut:
      type: object
      properties:
        avslutstyp:
          type: string
          description: ID för avslutstyp
        beslutstyp:
          type: string
          description: ID för beslutstyp
        beslutsutfall:
          type: string
          description: ID för beslutsutfall
      required:
        - avslutstyp
        - beslutstyp
        - beslutsutfall

    Kund:
      type: object
      properties:
        efternamn:
          type: string
        fornamn:
          type: string
        kon:
          type: string
          enum: [MAN, KVINNA]
        anstallning:
          $ref: "#/components/schemas/Anstallning"

    Anstallning:
      type: object
      properties:
        organisationsnummer:
          type: string
        organisationsnamn:
          type: string
        arbetstid_procent:
          type: integer
        anstallningsdag:
          type: string
          format: date
        sista_anstallningsdag:
          type: string
          format: date

    Ersattning:
      type: object
      properties:
        ersattning_id:
          type: string
          format: uuid
        ersattningstyp:
          type: string
        omfattning_procent:
          type: integer
        belopp:
          type: integer
        berakningsgrund:
          type: integer
        beslutsutfall:
          $ref: "#/components/schemas/Beslutsutfall"
        avslagsanledning:
          type: string
          nullable: true
        from:
          type: string
          format: date
        tom:
          type: string
          format: date

    UpdateErsattning:
      type: object
      properties:
        ersattning_id:
          type: string
          format: uuid
        yrkandestatus:
          type: string
          description: ID för yrkandestatus
      required:
        - ersattning_id
        - yrkandestatus

    Beslutsutfall:
      type: string
      enum: [JA, NEJ, FU]

    Referensdata:
      type: object
      properties:
        id:
          type: string
          description: ID för referensdata post
        kod:
          type: string
          description: Kod för referensdata post
        namn:
          type: string
          description: Namn på referensdata post
      example:
        id: "bae3c392-fbf4-4e16-8937-c27e93edf4e4"
        kod: "YRKANDESTATUS-1"
        namn: "Planerat"
